rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :productos

    #para que podamos estruccturar el codigo como si fuerean carpetas
  namespace :authentication, path: '', as:'' do
    resources :users, only: [:new, :create],path: '/register', path_names: {new: '/'}
    resources :sessions, only: [:new, :create, :destroy],path: '/login', path_names: {new: '/'}
  end

  resources :carritos, only: [:index, :create, :destroy], param: :producto_id
  resources :favorites, only: [:index, :create, :destroy], param: :producto_id
  resources :users, only: :show, path: '/user', param: :username
  resources :cargos, only: [:index, :new, :create]
  #resources :tallas, except: :show
  resources :tallas, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :categories, except: :show
  # Ruta raíz
  root to: 'productos#index'
  resources :productos, only: [:index, :show, :new, :create] # Agrega `:new` y `:create`
  resources :productitos, only: [] do
    collection do
      get 'index1'
      
      post 'send_to_queue'
      Rails.logger.debug "Categorías obtenidas: #{@categories.inspect}" # 👈 Agrega esta línea
      end
    end

  # Rutas para VentasOnlineController
  get 'ventas_online', to: 'ventas_online#index'
  post 'send_to_queue_ventas_online', to: 'ventas_online#send_to_queue'
  
  get '/productos/controllers/AccesoGoogle.js', to: 'productos#AccesoGoogle'
  
    resources :productos, except: [:destroy]

    resources :productitos do
      collection do
        get 'mensajes', to: 'productitos#mensajes'
        # get 'productitos/mensajes', to: 'productitos#mensajes'

      end
    end
    
    # get 'productitos/mensajes', to: 'productitos#mensajes', as: 'mensajes'
    get 'productitos/mensajes', to: 'productitos#mensajes', as: 'productitos_mensajes'


  


end

rails_app/app/models/carrito.rb
class Carrito < ApplicationRecord
  validates :user_id, uniqueness: { scope: :producto_id }
  belongs_to :user
  belongs_to :producto
end

rails_app/app/controllers/carritos_controller.rb
class CarritosController < ApplicationController
    skip_before_action :protect_pages_admin
    before_action :protect_pages_login    

    def index
        def index
            @carritos = Current.user.carritos.includes(:producto)
        end
    end
    
    def create
        Carrito.create(producto: producto, user: Current.user, cantidad: params[:cantidad])
        redirect_to productos_path, notice: "Producto añadido al carrito"
    end

    def destroy
        @carrito = Carrito.find_by(params[:id])
        if @carrito
          @carrito.destroy
          redirect_to carritos_path, notice: "Producto eliminado del carrito exitosamente."
        else
          redirect_to carritos_path, alert: "El producto no existe en tu carrito."
        end
      end
      

    private
    
    def carrito
        @carrito = Carrito.find(params[:id])
      end
    def producto
        @producto ||= Producto.find(params[:producto_id])
    end
end

rails_app/app/views/carritos/index.html.erb
<table class="table mt-3">
  <thead>
    <tr>
      <th>Producto</th>
      <th>Precio</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  <% if @carritos.present? %>
    <% @carritos.each do |carrito| %>
      <tr>
        <td><%= carrito.producto.titulo %></td>
        <td><%= carrito.producto.price %></td>
        <td>
          <% if Current.user && !Current.user.admin? %>
            <%= link_to "Eliminar", carrito_path(carrito), data: { turbo_method: :delete, turbo_confirm: 'Alerta, ¿estás seguro?' }, class: "btn btn-danger btn-sm" %>
          <% end %> 
        </td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="3">No hay productos en el carrito.</td>
    </tr>
  <% end %>
  </tbody>
</table>

<% if @carritos.present? %>
  <tr>
    <td colspan="2">Total:</td>
    <td><%= @carritos.sum { |carrito| carrito.producto.price } %></td>
    <br>
    <td>
      <%= link_to new_cargo_path(total: @carritos.sum { |carrito| carrito.producto.price }), class: "btn btn-sm d-inline-flex  custom-btn", style: "text-align: left; border: 2px solid #17E010;" do %>
        <%= image_tag 'icons/pagar.svg', width: 35, height: 35 %>
        <p class="ml-2" style="font-weight: bold;">Pagar</p>
      <% end %>
    </td>
  </tr>
<% end %>