rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :productos

    #para que podamos estruccturar el codigo como si fuerean carpetas
  namespace :authentication, path: '', as:'' do
    resources :users, only: [:new, :create],path: '/register', path_names: {new: '/'}
    resources :sessions, only: [:new, :create, :destroy],path: '/login', path_names: {new: '/'}
  end

  resources :carritos, only: [:index, :create, :destroy], param: :producto_id
  resources :favorites, only: [:index, :create, :destroy], param: :producto_id
  resources :users, only: :show, path: '/user', param: :username
  resources :cargos, only: [:index, :new, :create]
  #resources :tallas, except: :show
  resources :tallas, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :categories, except: :show
  # Ruta raíz
  root to: 'productos#index'
  resources :productos, only: [:index, :show, :new, :create] # Agrega `:new` y `:create`
  resources :productitos, only: [] do
    collection do
      get 'index1'
      
      post 'send_to_queue'
      Rails.logger.debug "Categorías obtenidas: #{@categories.inspect}" # 👈 Agrega esta línea
      end
    end

  # Rutas para VentasOnlineController
  get 'ventas_online', to: 'ventas_online#index'
  post 'send_to_queue_ventas_online', to: 'ventas_online#send_to_queue'
  
  get '/productos/controllers/AccesoGoogle.js', to: 'productos#AccesoGoogle'
  
    resources :productos, except: [:destroy]

    resources :productitos do
      collection do
        get 'mensajes', to: 'productitos#mensajes'
        # get 'productitos/mensajes', to: 'productitos#mensajes'

      end
    end
    
    # get 'productitos/mensajes', to: 'productitos#mensajes', as: 'mensajes'
    get 'productitos/mensajes', to: 'productitos#mensajes', as: 'productitos_mensajes'


  


end

rails_app/app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="flash <%= key %>" data-controller="flash">
      <%= value %>
    </div>
<% end %>

rails_app/app/views/shared/_header.html.erb
<div class="bg-white flex justify-between items-center px-2" data-controller="menu">
  <%= link_to productos_path do %>
    <!-- # agrandando el texto aqui 2 -- 4 -->
    
    <h1 class = "text-2xl font-bold text-teal-500" >Mega Tienda</h1>
  <% end %>
    
  
  <button class="sm:hidden" data-action="click->menu#open" ><%= image_tag 'icons/menu.svg', width: 35, height: 35 %></button>
  
  <!-- ver el estilo escritorio -->
  <div class="hidden sm:block " >
    <%= render partial: 'shared/items'%>
  </div>
  
  <!--ver el estilo movil-->
  <div class="sm:hidden  absolute bg-white top-0 rigth-0 shadow z-10 h-auto flex flex-col min-w-[35%] overflow-y-scroll ease-in-out duration-200 p-5 translate-x-full" data-menu-target="items" >
    <button class="mb-4" data-action="click->menu#close" ><%= image_tag 'icons/close.svg', width: 35, height: 35 %></button>
    <%= render partial: 'shared/items'%>
  </div>
</div>

rails_app/app/views/shared/_items.html.erb
<div class="flex flex-row">
  <% if Current.user && !Current.user.admin? %>
    <%= link_to  carritos_path , class: 'flex flex-row mx-2 text-teal-500 font-bold' do %>
      <%= image_tag 'icons/shop.svg', width: 30, height: 30, class: 'mr-2' %>
      <span>Carrito</span>
    <% end %>
  <% end %>
  <%= link_to "Pagos realizados", cargos_path, class:"mx-2 text-teal-500 font-bold" if Current.user && Current.user.admin? %>
  <%= link_to "Añadir producto", new_producto_path, class:"mx-2 text-teal-500 font-bold" if Current.user && Current.user.admin? %>
  <%= link_to "Categorias", categories_path, class:"mx-2 text-teal-500 font-bold" if Current.user && Current.user.admin? %>
  <%= link_to "Tallas", tallas_path, class:"mx-2 text-teal-500 font-bold" if Current.user && Current.user.admin? %>
  <%= link_to "Favoritos", favorites_path, class:"mx-2 text-teal-500 font-bold" if Current.user && !Current.user.admin? %>

  <% if Current.user.nil? %>
    <%= link_to "Login", new_session_path, class:"mx-2 text-teal-500 font-bold" %>
  <% end %>

  <%= link_to "Logout", session_path(Current.user.id), data: { turbo_method: :delete, turbo_confirm: "¿Está seguro?" }, class:"mx-2 text-teal-500 font-bold" if Current.user %>
</div>