rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :productos

    #para que podamos estruccturar el codigo como si fuerean carpetas
  namespace :authentication, path: '', as:'' do
    resources :users, only: [:new, :create],path: '/register', path_names: {new: '/'}
    resources :sessions, only: [:new, :create, :destroy],path: '/login', path_names: {new: '/'}
  end

  resources :carritos, only: [:index, :create, :destroy], param: :producto_id
  resources :favorites, only: [:index, :create, :destroy], param: :producto_id
  resources :users, only: :show, path: '/user', param: :username
  resources :cargos, only: [:index, :new, :create]
  #resources :tallas, except: :show
  resources :tallas, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :categories, except: :show
  # Ruta raíz
  root to: 'productos#index'
  resources :productos, only: [:index, :show, :new, :create] # Agrega `:new` y `:create`
  resources :productitos, only: [] do
    collection do
      get 'index1'
      
      post 'send_to_queue'
      Rails.logger.debug "Categorías obtenidas: #{@categories.inspect}" # 👈 Agrega esta línea
      end
    end

  # Rutas para VentasOnlineController
  get 'ventas_online', to: 'ventas_online#index'
  post 'send_to_queue_ventas_online', to: 'ventas_online#send_to_queue'
  
  get '/productos/controllers/AccesoGoogle.js', to: 'productos#AccesoGoogle'
  
    resources :productos, except: [:destroy]

    resources :productitos do
      collection do
        get 'mensajes', to: 'productitos#mensajes'
        # get 'productitos/mensajes', to: 'productitos#mensajes'

      end
    end
    
    # get 'productitos/mensajes', to: 'productitos#mensajes', as: 'mensajes'
    get 'productitos/mensajes', to: 'productitos#mensajes', as: 'productitos_mensajes'


  


end

rails_app/app/models/producto.rb
# class Producto < ApplicationRecord
#   belongs_to :category
#   include PgSearch::Model
#   pg_search_scope :search_full_text, against: {
#     titulo: 'A',
#     description: 'B'
#   }
  
#   ORDER_BY = {
#     newest: "created_at DESC",
#     expensive: "price DESC",
#     cheapest: "price ASC"
#   }

#   #un archivo adjunto foto
#   has_one_attached :photo
#   validates :titulo, presence: true
#   validates :description, presence: true
#   validates :price, presence: true
#   validates :color, presence: true
#   validates :stock, presence: true


#   # para guardar la imgen
#   # Método para obtener la URL de la imagen
#   # Método para obtener la URL de la imagen
#   # ✅ Método para obtener la URL de la imagen desde public/products/
# # ✅ Método para obtener la URL de la imagen
# def photo_url
#   photo_path.present? ? "/products/#{photo_path}" : "/images/placeholder.jpg"
#   # <%= image_tag "/app/asstproducts/#{producto.photo_path}", width: 200, class: "rounded-lg" %>
# end

#   #hacemos que un producto tiene varios favoritos, es decir un producto le puede gustar a varias personas
#   #y si se borra ese producto, sus favoritos tambien se borran
#   has_many :favorites, dependent: :destroy
#   #decimos que el modelo product pertenece a categorias
#   belongs_to :category

#   belongs_to :talla

#   has_many :carritos
  
#   def favorite!
#     favorites.create(user: Current.user)
#   end

#   def unfavorite!
#     favorite.destroy
#   end

#   def favorite
#     favorites.find_by(user: Current.user)
#   end
# end











class Producto < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_full_text, against: {
    titulo: 'A',
    description: 'B'
  }
  
  ORDER_BY = {
    newest: "created_at DESC",
    expensive: "price DESC",
    cheapest: "price ASC"
  }

  #un archivo adjunto foto
  has_one_attached :photo
  # validates :titulo, presence: true
  # validates :description, presence: true
  # validates :price, presence: true
  # validates :color, presence: true
  # validates :stock, presence: true
  # validates :imagen_url, presence: true
  validates :titulo, :description, :price, :color, :stock, :category_id, :talla_id, :imagen_url, presence: true
  #hacemos que un producto tiene varios favoritos, es decir un producto le puede gustar a varias personas
  #y si se borra ese producto, sus favoritos tambien se borran
  has_many :favorites, dependent: :destroy
  #decimos que el modelo product pertenece a categorias
  belongs_to :category

  belongs_to :talla

  has_many :carritos
  
  def favorite!
    favorites.create(user: Current.user)
  end

  def unfavorite!
    favorite.destroy
  end

  def favorite
    favorites.find_by(user: Current.user)
  end
end

rails_app/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  skip_before_action :protect_pages_admin, only: [:index, :show]

  def index
    @categories = Category.order(name: :asc).load_async
    @pagy, @productos = pagy_countless(FindProductos.new.call(producto_prams_index), items: 12)
    #@pagy, @productos = pagy(FindProductos.new.call(producto_prams_index), items: 12)

  end

  def new
    authorize!
    @producto = Producto.new
    @tallas = Talla.all.order(name: :asc)
  end

  def create
    authorize!
    @producto = Producto.new(producto_params)

    if @producto.save
      redirect_to productos_path, notice: "El producto ha sido creado correctamente"
    else
      render :new, status: :unprocessable_entity, alert: "El producto no ha sido creado correctamente"
    end
  end

  

  def show
    producto
  end

  def edit
    authorize!
    @producto = Producto.find(params[:id])
  end

  def update
    @producto = Producto.find(params[:id])
    if @producto.update(producto_params)
      redirect_to producto_path(@producto), notice: "El producto ha sido actualizado correctamente"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @producto = Producto.find(params[:id])
    if @producto
      @producto.destroy
      redirect_to productos_path, notice: "Producto eliminado con éxito", status: :see_other
    else
      redirect_to productos_path, alert: "El producto no existe"
    end
  end

  def add_to_cart
    if current_user
      product = Producto.find(params[:id])  # Asegurar que Producto existe
      current_user.cart_items.create(producto: product, quantity: 1)  # Corregido "producto" por "product"
      redirect_to productos_path, notice: 'Producto añadido al carrito'
    else
      redirect_to login_path, alert: 'Debes iniciar sesión para añadir productos al carrito'
    end
  end


  private

  def producto_params
    params.require(:producto).permit(:titulo, :description, :price, :color, :stock, :category_id, :talla_id, :imagen_url, :photo)
  end

  def producto_prams_index
    params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page, :favorites)
  end

  def producto
    @producto =  Producto.find(params[:id])
    #return @product
  end
  def index1
    @products = RabbitmqSubscriber.get_products
  end

  def send_to_queue
    categoria = params[:categoria]

    # Obtener todos los datos de los productos de la categoría usando ActiveRecord
    productos = Producto.joins(:category)
                        .where(categories: { name: categoria })
                        .select(:id, :titulo, :descripcion, :precio, :stock,:imagen_url) # Selecciona todos los datos necesarios

    if productos.empty?
      flash[:alert] = "No hay productos en la categoría #{categoria}."
      redirect_to index1_productitos_path and return
    end

    productos_json = productos.as_json # Convierte los productos a formato JSON

    begin
      RabbitmqPublisher.publish(productos_json, categoria)
      flash[:notice] = "Productos de la categoría #{categoria} enviados a RabbitMQ."
    rescue StandardError => e
      flash[:alert] = "❌ Error al enviar productos a RabbitMQ: #{e.message}"
    end

    redirect_to index1_productitos_path
  end

  
end

rails_app/app/helpers/productos_helper.rb
module ProductosHelper
end

rails_app/app/views/productos/_category.html.erb
<%= link_to productos_path(category_id: category.id), 
    class: "category bg-green-300 hover:bg-green-200 flex items-center  text-black text-gray-600 px-4 py-2 rounded-xl drop-shadow-sm w-auto" do %>
  <%= category.name %>&nbsp;
<% end %>

rails_app/app/views/productos/_favorite.html.erb
<div id="favorite">
    <% if @producto.favorite%>
    <%= link_to '🖤', favorite_path(@producto.id), data: { turbo_method: :delete } %>
    <% else %>
    <%= link_to '❤️', favorites_path(producto_id: @producto.id), data: { turbo_method: :post } %>
    <% end %>
</div>

rails_app/app/views/productos/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with(model: @producto, local: true, html: { multipart: true }) do |form| %>
        <% if @producto.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

            <ul>
              <% @producto.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="card">
          <div class="card-body">
            
            <div class="field">
              <%= form.label :titulo %>
              <%= form.text_field :titulo, class: "form-control" %>
              <% if @producto.errors[:titulo].any? %>
                <div class="error-message"><%= @producto.errors[:titulo].first %></div>
              <% end %>
            </div>

            <div class="field">
              <%= form.label :description %>
              <%= form.text_area :description, class: "form-control" %>
              <% if @producto.errors[:description].any? %>
                <div class="error-message"><%= @producto.errors[:description].first %></div>
              <% end %>
            </div>

            <div class="field">
              <%= form.label :price %>
              <%= form.number_field :price, class: "form-control" %>
            </div>

            <div class="field">
              <%= form.label :color %>
              <%= form.text_field :color, class: "form-control" %>
              <% if @producto.errors[:color].any? %>
                <div class="error-message"><%= @producto.errors[:color].first %></div>
              <% end %>
            </div>

            <div class="field">
              <%= form.label :stock %>
              <%= form.number_field :stock, class: "form-control" %>
              <% if @producto.errors[:stock].any? %>
                <div class="error-message"><%= @producto.errors[:stock].first %></div>
              <% end %>
            </div>

            <div class="field">
              <%= form.label :category_id, "Categoría" %>
              <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name, { prompt: "Seleccione una categoría" }, class: "form-control" %>
            </div>

            <div class="field">
              <%= form.label :talla_id, "Talla" %>
              <%= form.collection_select :talla_id, Talla.all.order(name: :asc), :id, :name, { prompt: "Seleccione una talla" }, class: "form-control" %>
            </div>

            <div class="field">
              <%= form.label :imagen_url %>
              <%= form.text_field :imagen_url, class: "form-control" %>
            </div>

            <div class="field">
              <%= form.label :photo, "Seleccionar imagen" %>
              <label for="photo-upload" class="bg-blue-500 text-white px-4 py-2 rounded-lg cursor-pointer hover:bg-blue-700">
                Elegir archivo
              </label>
              <%= form.file_field :photo, id: "photo-upload", class: "hidden" %>

              <% if @producto.photo.attached? %>
                <div class="mt-2">
                  <%= link_to url_for(@producto.photo) do %>
                    <%= image_tag @producto.photo, width: 200 %>
                  <% end %>
                </div>
                <p>
                  Archivo actual: 
                  <%= link_to @producto.photo.filename.to_s, url_for(@producto.photo), target: "_blank", class: "text-blue-600 hover:underline font-bold" %>
                </p>
              <% else %>
                <!-- Mostrar mensaje solo si NO hay imagen -->
                <div class="mt-2">
                  <span class="bg-gray-300 text-gray-700 px-3 py-1 rounded-lg text-sm cursor-pointer">
                    Ninguna imagen seleccionada
                  </span>
                </div>
              <% end %>
            </div>

            <div class="mt-3 text-center">
              <%= form.submit "Guardar", class: "btn btn-primary" %>
            </div>

          </div> <!-- Cierre de .card-body -->
        </div> <!-- Cierre de .card -->
      <% end %> <!-- Cierre de form_with -->
    </div> <!-- Cierre de .col-md-6 -->
  </div> <!-- Cierre de .row -->
</div> <!-- Cierre de .container -->

rails_app/app/views/productos/_producto.html.erb
<%= link_to producto_path(producto.id), class:"Producto bg-white mb-2 rounded sm:w-[calc(33.33333%_-_.5rem)] lg:w-[calc(25%_-_.5rem)] p-0.5 h-150 "  , 'data-turbo-frame': '_top' do %>
  <%= image_tag producto.photo.attached? ? producto.photo: 'placeholder.jpg',class:"w-full h-50 object-cover rounded-2xl"  %>
  <div class="m-3">
    <h2 class="font-bold txt-xl"><%= producto.titulo %></h2>
    <p class="text-gray-500 text-sm mt-2"><%= producto.description %></p>
    <div class="flex justify-between ">
      <span class="font-bold text-red-600">S/.<%= producto.price %></span>
      <div class="bg-green-500 rounded">
        <%= image_tag 'icons/shop.svg', width: 35, height: 35, alt: 'Ver productos' %>
      </div>
    </div>
  </div>
<% end %>

rails_app/app/views/productos/edit.html.erb
<%=render 'form'%>

rails_app/app/views/productos/index.html.erb
<%= turbo_frame_tag 'home' do%>
  <%= form_with url: productos_path, method: :get, class:" w-[50%] flex flex-column mx-auto " do |form|%>
    <%= form.text_field :query_text, placeholder: 'Buscar producto',
    onChange: 'this.form.requestSubmit()',value: params[:query_text],
    class:" px-4 py-3 mt-4 rounded-2xl "
    %>

    <div class="flex items-center p-2 ">
      <%= form.number_field :min_price, placeholder: 'MinPrice',
      onChange: 'this.form.requestSubmit()',value: params[:min_price],
      class:" flex-[1_1_50%] rounded-xl border-gray-200 py-2 px-3  my-4"
      %>

      <%= form.number_field :max_price, placeholder: 'MaxPrice',
      onChange: 'this.form.requestSubmit()',value: params[:max_price],
      class:" flex-[1_1_50%] rounded-xl border-gray-200 py-2 px-3 my-4 mx-2"
      %>

      <%= form.select :order_by, options_for_select([["Recientes","newest"],
      ["Más Caros","expensive"],["Más Baratos","cheapest"]],params[:order_by]),{},
      {onChange: 'this.form.requestSubmit()',
      class:" flex-[1_1_50%] rounded-xl border-gray-200 py-2 px-3 my-4"}%>
    </div>
  <% end %>

<!-- eliminar el margen superior (my-4) y reemplazarlo por mt-0 (margen superior cero).   -->
  <div class="flex flex-wrap justify-center gap-2 py-4 px-4 mt-0 mb-4 w-[90%] m-auto">
    <%= link_to 'All', productos_path, class:' flex items-center justify-center border-1 border-gray-500  text-gray-600 rounded-xl drop-shadow-sm hover:bg-gray-300 py-2 px-4 ' %>
    <%= render partial: 'category', collection: @categories%>
  </div>

  <%= turbo_frame_tag 'productos', class:" flex flex-col m-2 " do %>
    <!-- llamamos products a nuestro frama y le pasamos que pagina es la actual-->
    <%= turbo_frame_tag "productos-#{@pagy.page}", class: ' bg-gray-200 p-2 productos flex flex-col w-[90%] m-auto sm:flex-row sm:flex-wrap sm:gap-x-2' do%>
      <%=render partial: 'producto', collection: @productos %>
      <!-- hacemos un turbo frame anidado para la pagination que tendrá d nombre productos
      y el numero de pagina siguiente-->
      <%= turbo_frame_tag "productos-#{@pagy.next}", class: 'productos flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2', src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next%>
    <% end %>
  <% end %>

<% end %>


  
  

rails_app/app/views/productos/index1.html.erb
<h1>Productos Recibidos</h1>

<table border="1">
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Stock</th>
    </tr>

    <% @products.each do |product| %>
    <tr>
        <td><%= product["id"] %></td>
        <td><%= product["name"] %></td>
        <td><%= product["price"] %></td>
        <td><%= product["stock"] %></td>
    </tr>
    <% end %>
</table>

rails_app/app/views/productos/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1 class="text-center text-2xl font-bold text-teal-500">CREAR PRODUCTO</h1>
    </div>
  </div>
</div>

<%=render 'form'%>

rails_app/app/views/productos/show.html.erb
<div class="bg-slate-400 w-[40%] m-auto mt-4 flex p-3 rounded">
  <% if @producto.photo.attached? %>
    <%= image_tag url_for(@producto.photo), width: 200, class: "rounded-l" %>
  <% else %>
    <%= image_tag 'placeholder.jpg', width: 200, class: "rounded-l" %>
  <% end %>
  <div class="bg-green-700 flex flex-column w-full p-4 rounded-r">
    <h1 class='title text-center font-bold my-3'><%= @producto.titulo %></h1>
    <p class='description'>Detalles : <%= @producto.description %></p>
    <p class='color'>Color : <%= @producto.color %></p>
    <p class='stock'>Stock : <%= @producto.stock %></p>
    <span class='price'>Precio : <%= @producto.price %></span>
  </div>
</div>


<% unless Current.user && Current.user.admin? %>
  <%= link_to "#", id: "add-to-cart-link", class: "flex items-center", data: { turbo_method: :post } do %>
    <div class="flex items-center bg-green-600 rounded p-2 hover:bg-green-400">
      <%= image_tag 'icons/shop.svg', width: 35, height: 35 %>
      <p class="ml-2">Añadir al carrito</p>
    </div>
  <% end %>
<% end %>

<div id="quantity-modal" class="modal fixed inset-0 z-10 w-screen overflow-y-auto hidden">
  <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
    <div class="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
      <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
        <div class="sm:flex sm:items-start">
          <div class="mx-auto flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
            <svg class="h-6 w-6 text-red-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
            </svg>
          </div>
          <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left">
            <h3 class="text-base font-semibold leading-6 text-gray-900" id="modal-title">Cantidad de productos a comprar?</h3>
            <div class="mt-2">
              <p class="text-sm text-gray-500">Existencias en stock: <%= @producto.stock %></p>
            </div>
            <%= form_with(url: carritos_path, method: :post, id: "add-to-cart-form") do |form| %>
              <%= form.hidden_field :producto_id, value: @producto.id %>
              <%= form.label :Nº %>
              <%= form.number_field :quantity, class: "quantity-input", min: 1 %>
              <%= form.submit "Agregar al carrito", class: "btn-submit inline-flex w-full justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 sm:ml-3 sm:w-auto" %>
              
              <button type="button" class="close mt-3 inline-flex w-full justify-center rounded-md bg-gray-200 px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-300 sm:mt-0 sm:w-auto">Cancelar</button>
            <% end %>
          </div>
        </div>
      </div>
      <div class="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
        <button type="button" class="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:mt-0 sm:w-auto">Cancelar</button>
      </div>
    </div>
  </div>
</div>

<% if Current.user && Current.user.admin? %>
  <div class="flex w-[100vh] justify-center m-auto mt-2">
    <%= link_to "Editar", edit_producto_path(@producto), class: "btn btn-primary btn-sm mr-2" %>
    <%= link_to "Delete", producto_path(@producto), data: { turbo_method: :delete, turbo_confirm: 'Alerta, ¿estás seguro?' }, class: "btn btn-danger btn-sm" %>
  </div>
<% end %>

<% unless Current.user && Current.user.admin? %>
  <%= render partial: 'favorite', locals: { producto: @producto } %>
<% end %>

<script>
  // Get the modal
  var modal = document.getElementById("quantity-modal");

  // Get the link that opens the modal
  var link = document.getElementById("add-to-cart-link");

  // Get the form inside the modal
  var form = document.getElementById("add-to-cart-form");

  // Get the input field for quantity
  var quantityInput = document.querySelector(".quantity-input");

  // When the user clicks the link, open the modal
  link.onclick = function(event) {
    event.preventDefault(); // Evitar el comportamiento predeterminado del enlace
    event.stopPropagation(); // Evitar la propagación del evento
    modal.style.display = "block";
  }

  // When the user submits the form, close the modal
  form.onsubmit = function() {
    modal.style.display = "none";
  }

  // When the user clicks on <span> (x), close the modal
  var span = document.getElementsByClassName("close")[0];
  span.onclick = function() {
    modal.style.display = "none";
  }

  // When the user clicks anywhere outside of the modal, close it
  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  }

  // Submit the form when clicking "Agregar al carrito"
  var submitBtn = document.querySelector(".btn-submit");
  submitBtn.addEventListener("click", function() {
    // Set the value of the hidden input field to the quantity input value
    document.getElementById("quantity").value = quantityInput.value;
    // Submit the form
    form.submit();
  });
</script>