rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :productos

    #para que podamos estruccturar el codigo como si fuerean carpetas
  namespace :authentication, path: '', as:'' do
    resources :users, only: [:new, :create],path: '/register', path_names: {new: '/'}
    resources :sessions, only: [:new, :create, :destroy],path: '/login', path_names: {new: '/'}
  end

  resources :carritos, only: [:index, :create, :destroy], param: :producto_id
  resources :favorites, only: [:index, :create, :destroy], param: :producto_id
  resources :users, only: :show, path: '/user', param: :username
  resources :cargos, only: [:index, :new, :create]
  #resources :tallas, except: :show
  resources :tallas, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :categories, except: :show
  # Ruta raíz
  root to: 'productos#index'
  resources :productos, only: [:index, :show, :new, :create] # Agrega `:new` y `:create`
  resources :productitos, only: [] do
    collection do
      get 'index1'
      
      post 'send_to_queue'
      Rails.logger.debug "Categorías obtenidas: #{@categories.inspect}" # 👈 Agrega esta línea
      end
    end

  # Rutas para VentasOnlineController
  get 'ventas_online', to: 'ventas_online#index'
  post 'send_to_queue_ventas_online', to: 'ventas_online#send_to_queue'
  
  get '/productos/controllers/AccesoGoogle.js', to: 'productos#AccesoGoogle'
  
    resources :productos, except: [:destroy]

    resources :productitos do
      collection do
        get 'mensajes', to: 'productitos#mensajes'
        # get 'productitos/mensajes', to: 'productitos#mensajes'

      end
    end
    
    # get 'productitos/mensajes', to: 'productitos#mensajes', as: 'mensajes'
    get 'productitos/mensajes', to: 'productitos#mensajes', as: 'productitos_mensajes'


  


end

rails_app/app/models/talla.rb
class Talla < ApplicationRecord
    validates :name, presence: true
    has_many :productos, dependent: :restrict_with_exception
end

rails_app/app/controllers/tallas_controller.rb
class TallasController < ApplicationController
  before_action :authorize!
  def index
    @tallas = Talla.all
  end


  # GET /tallas/new
  def new
    @talla = Talla.new
  end

  # GET /tallas/1/edit
  def edit
    talla
  end

  # POST /tallas or /tallas.json
  def create
    @talla = Talla.new(talla_params)

    respond_to do |format|
      if @talla.save
        format.html { redirect_to tallas_url, notice: "Talla was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tallas/1 or /tallas/1.json
  def update
    if talla.update(talla_params)
      redirect_to tallas_url, notice: "CATEGORIA ACTUALIZADA CORRECTAMENTE" 
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tallas/1 or /tallas/1.json
  def destroy
    talla.destroy
    redirect_to tallas_url, alert: "CATEGORIA ELIMINADA CORRECTAMENTE"
     
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def talla
      @talla = Talla.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def talla_params
      params.require(:talla).permit(:name)
    end
end

rails_app/app/helpers/tallas_helper.rb
module TallasHelper
end

rails_app/app/views/tallas/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with(model: talla) do |form| %>
        <div class="card">
          <div class="card-body">
            <div class="field">
              <%= form.label :name %>
              <%= form.text_field :name, class: "form-control" %>
              <% if talla.errors[:name].any? %>
                <div class="error-message"><%= talla.errors[:name].first %></div>
              <% end %>
            </div>

            <div class="mt-3 text-center">
              <%= form.submit class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

rails_app/app/views/tallas/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 text-center text-2xl font-bold text-teal-500">
      <h1>Editar talla</h1>
    </div>
  </div>
</div>
<%= render "form", talla: @talla %>

<br>


<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= link_to tallas_path, class: "btn d-flex align-items-center custom-btn", style: "text-align: left; border: 2px solid #17E010;" do %>
        <%= image_tag 'icons/atras.svg', width: 35, height: 35 %>
        <p class="ml-2" style="font-weight: bold;">Back to tallas</p>
      <% end %>
    </div>
  </div>
</div>

rails_app/app/views/tallas/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1 class="text-center text-2xl font-bold text-teal-500">Tallas</h1>
    </div>
  </div>
</div>
<table class="table mt-3">
  <% @tallas.each do |talla| %>
    <tr id="<%= dom_id(talla) %>">
      <td><%= talla.name %></td>
      <td><%= link_to "Edit", edit_talla_path(talla), class: "btn btn-primary btn-sm"  %></td>
      <td><%= link_to "Delete", talla_path(talla), data: { turbo_method: :delete, turbo_confirm: "Alerta, ¿estás seguro?" }, class: "btn btn-danger btn-sm" %></td>
    </tr>
  <% end %>
</table>


<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= link_to new_talla_path, class: "btn d-flex align-items-center custom-btn",  style: "text-align: left; border: 2px solid #17E010;" do %>
        <%= image_tag 'icons/add.svg', width: 35, height: 35 %>
        <p class="ml-2" style="font-weight: bold;">Nueva talla</p>
      <% end %>
    </div>
  </div>
</div>

rails_app/app/views/tallas/new.html.erb
<h1>New talla</h1>

<%= render "form", talla: @talla %>

<br>

<div>
  <%= link_to "Back to tallas", tallas_path %>
</div>